name: Claude Code Issue Fix

on:
  issues:
    types: [labeled]

jobs:
  claude-label-fix:
    uses: fractureinc/claude-code-github-action/.github/workflows/claude-label-fix.yml@v0.5.6
    with:
      issue-label: 'claude-fix'        # Must match the label used
      branch-prefix: 'fix'             # Optional prefix for branch names
      debug-mode: false                # Optional toggle for logging
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
