name: Copilot Agent Basic Write Test
on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  write-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Echo test
        run: echo "Copilot agent permission test"
